advice_agent_type: "learned_augmented"
expert_path: "experiments/2024_10_11_FINETUNING/gravity/baselines_sweep/gravity_bias_easiest_noise-0.005_lr-0.0005_another/version_10_0/ckpt_policy/model-epoch=86000-val_reward=0.49.ckpt"
base_policy: "experiments/2024_09_26_FINAL_EXPLORATION/20K_labels/version_0_0/ckpt_policy/model-epoch=9930000-val_reward=0.46.ckpt"
seed: 20
env_type: "Cuesim/ThreeBallHard-Cuelearner"
env_options:
  physics.gravity_bias_y: 0.005
trainer:
  log_dir: "experiments/2024_10_11_FINETUNING/gravity/plot_high_res/gravity_bias_easiest_w_advice_small_network_high_precision"
  max_steps: 10000
  start_steps: 0
  buffer_size: 10000
  advice_noise: 0.0
  adv_update_after: 20
  adv_update_every: 20
  advice_probability: 1.0
  eval_every: 100
  eval_steps: 10000
  verbose: true
  print_every: 100
  advice_checkpoint_options:
    save_best: true
    save_last: true
    save_period: 50
advice_cloner:
  args:
    batch_size: 10
    hidden_sizes_advice_cloner:
    - 400
    - 300
    advice_step_size: 0.1
    advice_max_steps: 3
    advice_termination_threshold: 0.0
    advice_search_width: 1.0
    residual_scaling_factor: 400
    fit_policy: "restarts"
    optimizer: "adam"
    learning_rate: 0.001
    weight_decay: 0.
    gradient_clipping: 0.5
    patience: 10
    advice_training_sampling: "bisection"

